Repository project-Volunteer/BackEnd, pull requests merged in 2023-05, with the labels that each got.

#24 feat: 봉사 모집 글 참여자 관리 기능 및 API 구현
  .gitignore
  build.gradle
  src/main/java/project/volunteer/domain/participation/api/ParticipationController.java
  src/main/java/project/volunteer/domain/participation/api/dto/ParticipantAddParam.java
  src/main/java/project/volunteer/domain/participation/api/dto/ParticipantRemoveParam.java
  src/main/java/project/volunteer/domain/participation/api/dto/ParticipationParam.java
  src/main/java/project/volunteer/domain/participation/application/ParticipationService.java
  src/main/java/project/volunteer/domain/participation/application/ParticipationServiceImpl.java
  src/main/java/project/volunteer/domain/participation/dao/ParticipantRepository.java
  src/main/java/project/volunteer/domain/participation/domain/Participant.java
  src/main/java/project/volunteer/domain/recruitment/application/RecruitmentDtoServiceImpl.java
  src/main/java/project/volunteer/domain/recruitment/application/RecruitmentServiceImpl.java
  src/main/java/project/volunteer/domain/recruitment/dao/RecruitmentRepository.java
  src/main/java/project/volunteer/global/common/component/State.java
  src/main/java/project/volunteer/global/error/exception/BusinessException.java
  src/main/java/project/volunteer/global/error/exception/ErrorCode.java
  src/main/java/project/volunteer/global/error/exhadler/ParticipationControllerAdvice.java
  src/main/java/project/volunteer/global/util/SecurityUtil.java
  src/main/resources/messages.properties
  src/test/java/project/volunteer/domain/participation/api/ParticipationControllerTest.java
  src/test/java/project/volunteer/domain/participation/application/ParticipationServiceImplTest.java
  src/test/java/project/volunteer/domain/recruitment/api/RecruitmentControllerTestForQuery.java
  src/test/java/project/volunteer/domain/recruitment/application/RecruitmentDtoServiceImplTest.java
  src/test/java/project/volunteer/global/test/WithMockCustomUser.java
  src/test/java/project/volunteer/global/test/WithMockCustomUserSecurityContextFactory.java
Labels: 문서, 기능, 리팩토링, 테스트

#29 feat: 봉사 팀원 인원 검증 로직 추가
  src/main/java/project/volunteer/domain/participation/application/ParticipationServiceImpl.java
  src/main/java/project/volunteer/domain/participation/dao/ParticipantRepository.java
  src/main/java/project/volunteer/domain/recruitment/dao/RecruitmentRepository.java
  src/main/java/project/volunteer/domain/recruitment/domain/Recruitment.java
  src/main/java/project/volunteer/global/config/SecurityConfig.java
  src/main/java/project/volunteer/global/error/exception/BusinessException.java
  src/main/java/project/volunteer/global/error/exception/ErrorCode.java
  src/main/resources/messages.properties
  src/test/java/project/volunteer/domain/participation/api/ParticipationControllerTest.java
  src/test/java/project/volunteer/domain/participation/application/ParticipationServiceImplTest.java
Labels: 문서, 기능, 리팩토링, 테스트

#31 refactor: 봉사 모집글 상세조회 DTO 수정 사항을 반영하다.
  src/main/java/project/volunteer/domain/image/dao/ImageRepository.java
  src/main/java/project/volunteer/domain/participation/application/ParticipationServiceImpl.java
  src/main/java/project/volunteer/domain/participation/dao/ParticipantRepository.java
  src/main/java/project/volunteer/domain/recruitment/api/dto/request/RecruitmentRequest.java
  src/main/java/project/volunteer/domain/recruitment/application/RecruitmentDtoServiceImpl.java
  src/main/java/project/volunteer/domain/recruitment/application/dto/ParticipantDetails.java
  src/main/java/project/volunteer/domain/recruitment/application/dto/ParticipantState.java
  src/main/java/project/volunteer/domain/recruitment/application/dto/RecruitmentDetails.java
  src/main/java/project/volunteer/global/config/SecurityConfig.java
  src/test/java/project/volunteer/domain/recruitment/api/RecruitmentControllerTestForQuery.java
  src/test/java/project/volunteer/domain/recruitment/api/RecruitmentControllerTestForWrite.java
  src/test/java/project/volunteer/domain/recruitment/application/RecruitmentDtoServiceImplTest.java
Labels: 버그, 문서, 기능, 리팩토링, 테스트

#32 refactor: 봉사 모집 글 참여자 리스트 조회 쿼리 최적화를 한다.
  .gitignore
  src/main/java/project/volunteer/domain/image/domain/Image.java
  src/main/java/project/volunteer/domain/participation/dao/ParticipantRepository.java
  src/main/java/project/volunteer/domain/participation/dao/dto/ParticipantStateDetails.java
  src/main/java/project/volunteer/domain/recruitment/api/RecruitmentController.java
  src/main/java/project/volunteer/domain/recruitment/application/RecruitmentDtoServiceImpl.java
  src/main/java/project/volunteer/global/aop/LogAspect.java
  src/main/java/project/volunteer/global/aop/LogExecutionTime.java
  src/test/java/project/volunteer/domain/recruitment/api/RecruitmentControllerTestForQuery.java
  src/test/java/project/volunteer/domain/recruitment/performance/MockData.java
  src/test/java/project/volunteer/domain/recruitment/performance/RecruitmentDetailPerformanceTest.java
  src/test/resources/application.yml
Labels: 문서, 기능, 리팩토링, 테스트

#33 feat: 봉사 모집 글 삭제 권한 검증 기능을 추가하다
  src/main/java/project/volunteer/domain/recruitment/application/RecruitmentServiceImpl.java
  src/main/java/project/volunteer/domain/user/domain/User.java
  src/test/java/project/volunteer/domain/recruitment/application/RecruitmentServiceImplTestForEdit.java
  src/test/java/project/volunteer/global/test/WithMockCustomUserSecurityContextFactory.java
  src/test/resources/application-performance.yml
  src/test/resources/application-test.yml
Labels: 기능, 리팩토링

#38 feat: Mypage의 봉사 모집글 승인대기 리스트 및 모집 현황 API 구현
  src/main/java/project/volunteer/domain/user/api/UserController.java
  src/main/java/project/volunteer/domain/user/api/dto/response/UserJoinRequestListResponse.java
  src/main/java/project/volunteer/domain/user/api/dto/response/UserRecruitingListResponse.java
  src/main/java/project/volunteer/domain/user/application/UserService.java
  src/main/java/project/volunteer/domain/user/application/UserServiceImpl.java
  src/main/java/project/volunteer/domain/user/dao/UserRepository.java
  src/main/java/project/volunteer/domain/user/dao/queryDto/UserQueryDtoRepository.java
  src/main/java/project/volunteer/domain/user/dao/queryDto/UserQueryDtoRepositoryImpl.java
  src/main/java/project/volunteer/domain/user/dao/queryDto/dto/UserRecruitingQuery.java
  src/main/java/project/volunteer/domain/user/dao/queryDto/dto/UserRecruitmentJoinRequestQuery.java
  src/test/java/project/volunteer/domain/user/api/UserControllerJoinRequestTest.java
  src/test/java/project/volunteer/domain/user/api/UserControllerRecruitingTest.java
  src/test/java/project/volunteer/domain/user/application/UserServiceImplTest.java
Labels: 기능, 테스트

#46 chore: 임시 배포를 진행한다.
  Dockerfile
  src/main/java/project/volunteer/domain/user/dao/queryDto/UserQueryDtoRepository.java
  src/main/java/project/volunteer/domain/user/dao/queryDto/UserQueryDtoRepositoryImpl.java
Labels: 문서, 기능
